CREATE DATABASE MED_DISTRIBUTION;

CREATE TABLE USERS (
   id serial PRIMARY KEY,
   email VARCHAR ( 50 ) UNIQUE NOT NULL,
   password VARCHAR (255) NOT NULL,
   role VARCHAR (255) NOT NULL,
   refresh_token VARCHAR (255),
   created_at TIMESTAMP NOT NULL DEFAULT NOW(),
   updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);